server:
  net: 1 # 1: mainnet 2: testnet
  http_server_addr: ":8118"
notice:
  webhook_lark_err: ""
chain:
  ckb_url: "http://127.0.0.1:8114"
  index_url: "http://127.0.0.1:8116"
  current_block_number: 4872287 # 4872287: mainnet 1927285: testnet
  confirm_num: 4 # confirm nums before written into DB
  concurrency_num: 100
db:
  mysql:
    log_mode: true
    addr: "127.0.0.1" # 172.17.0.1: docker 182.17.0.1: docker-compose
    user: "root"
    password: "123456"
    db_name: "das_database"
    max_open_conn: 100
    max_idle_conn: 50
gecko_ids:
  - "nervos-network"
  - "ethereum"
  - "bitcoin"
  - "tron"
  - "_wx_cny_"
  - "binancecoin"
  - "matic-network"
