version: '3'
networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: 182.17.0.0/16
          gateway: 182.17.0.1

services:
  bit-database:
    image: slagga/bit-database:latest
    restart: always
    working_dir: /app
    entrypoint: [ "/app/bit-database", "--config", "/app/config/config.yaml" ]
    ports:
      - "8118:8118"
      - "9118:9118"
    volumes:
      - $PWD/bit-database/config/config.yaml:/app/config/config.yaml
    depends_on:
      - mysql1
    networks:
      - mynetwork

  mysql1:
    image: mysql/mysql-server:8.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - $PWD/bit-database/mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bit_database
      TZ: Asia/Shanghai
      # This allows ip ranges from 182.17.0.1 to 182.17.255.255 to connect to root
      MYSQL_ROOT_HOST: "182.17.%.%"
    networks:
      - mynetwork

  bit-indexer:
    image: slagga/bit-indexer:latest
    restart: always
    working_dir: /app
    entrypoint: [ "/app/bit-indexer", "--config", "/app/config/config.yaml" ]
    ports:
      - "8121:8121"
      - "8122:8122"
      - "8123:8123"
    volumes:
      - $PWD/bit-indexer/config/config.yaml:/app/config/config.yaml
    depends_on:
      - mysql2
      - redis
    networks:
      - mynetwork

  mysql2:
    image: mysql/mysql-server:8.0
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - $PWD/bit-indexer/mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bit_account_indexer
      TZ: Asia/Shanghai
      # This allows ip ranges from 182.17.0.1 to 182.17.255.255 to connect to root
      MYSQL_ROOT_HOST: "182.17.%.%"
    networks:
      - mynetwork

  redis:
    image: redis:5.0
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork
